spring.application.name=erp

spring.datasource.url=jdbc:mysql://localhost:3306/optimus_erp_p33?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
